
DROP TABLE INFORMATIONS_UTILISATEUR CASCADE CONSTRAINTS ;
DROP TABLE INGREDIENTS CASCADE CONSTRAINTS;
DROP TABLE UTILISATEURS CASCADE CONSTRAINTS;
DROP TABLE TYPE_ABONNEMENTS CASCADE CONSTRAINTS;
DROP TABLE CALENDRIER CASCADE CONSTRAINTS;
DROP TABLE ABONNEMENTS CASCADE CONSTRAINTS;
DROP TABLE MENUS CASCADE CONSTRAINTS;
DROP TABLE REPAS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTS_REPAS CASCADE CONSTRAINTS;
DROP TABLE REPAS_MENUS CASCADE CONSTRAINTS;