INSERT INTO
INGREDIENTS( id_ingredient,nom_ingredient)
    VALUES('IN001','Tomate');
    VALUES('IN002','Poisson');
    VALUES('IN003','Riz');
    VALUES('IN004','Epice');
    VALUES('IN005','Condiments verts');
    VALUES('IN006','Ails');
    VALUES('IN007','Oignons');
    VALUES('IN008','Crabes');
    VALUES('IN009','Pommes de Terre');
    VALUES('IN010','Yaourt');
    VALUES('IN011','Pomme_fruit');
    VALUES('IN012','Banane');
    VALUES('IN013','Choux');
    VALUES('IN014','Courgette');
    VALUES('IN015','Carotte');
    VALUES('IN016','Poulet');
    VALUES('IN017','Okok');
    VALUES('IN018','Pistache');
    VALUES('IN019','Crevettes');
    VALUES('IN20','Manioc');
    VALUES('IN021','Viande de boeuf');
    VALUES('IN022','Huile_rouge');
    VALUES('IN023','Legumes');
    VALUES('IN024','Macabo');
    VALUES('IN025','Morue');
    VALUES('IN026','Ananas');
    VALUES('IN027','Oeufs');
    VALUES('IN028','Mais');
    VALUES('IN029','Couscous manioc');
    VALUES('IN030','Gombo');
    VALUES('IN031','Ndolè');
    VALUES('IN032','Arrachides');
    VALUES('IN033','Melon');
    VALUES('IN034','Plantain');
    VALUES('IN035','Baton de manioc');
    VALUES('IN036','Conconbre');
    VALUES('IN037','Aubergine');
    VALUES('IN038','Django');
    VALUES('IN039','Piment');
    VALUES('IN040','Feuille de kwem');
    VALUES('IN041','Laitue');
    VALUES('IN042','Miondo');
    VALUES('IN043','Ignames');
    VALUES('IN044','Viande de lapin');