INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN010','RE001');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN026','RE001');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN017','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN021','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN020','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN018','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN019','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN022','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE002');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN002','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN012','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE003');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN030','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN021','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN028','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE004');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN016','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN003','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN015','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN014','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN036','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN037','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN046','RE005');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN040','RE006');                    

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN018','RE006');                               

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE006');                        

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN024','RE006');                         

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN028','RE006');                           

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN025','RE006');                          

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE007');                          

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE007');            

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE007');                         

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE007'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE007'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN002','RE007'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN003','RE007'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN009','RE008');                   

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN015','RE008'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN033','RE008');                           

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE008'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN013','RE008');                  

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN047','RE008'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN016','RE009');                    

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE009');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN003','RE009');                    

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN016','RE010');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN003','RE010');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN024','RE010');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE010');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE010');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN002','RE011');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE011');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN034','RE011');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN013','RE012');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN014','RE012');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE012');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE012');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN036','RE012');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN023','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN025','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN024','RE013');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN010','RE015');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN011','RE015');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE014');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN009','RE014');             

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN008','RE014');                 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE014'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE014'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE014'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN002','RE016'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE016'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN034','RE016'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE016'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE017');    

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN016','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN015','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN003','RE017'); 

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN002','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN009','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE018');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN048','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN049','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN015','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN036','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN048','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN013','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN050','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN041','RE019');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN031','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN032','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN021','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN042','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN004','RE020');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN046','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN051','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN001','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN005','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN045','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN006','RE021');

INSERT INTO
INGREDIENTS_REPAS(id_ingredient,id_repas)
VALUES('IN007','RE021');