INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT001',
    'Kenefack',
    'Jonnathan',
    '17/02/92',
    'M', 
    'kenejonn@gmail.com',
    'ken89Joh17',
    '01/01/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT002',
    'Kenfack',
    'Jonan',
    '17/02/02',
    'M', 
    'kenjonan@gmail.com',
    'jonan02',
    '23/02/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT003',
    'Temfack',
    'Joel',
    '17/01/99',
    'M', 
    'joe@gmail.com',
    'temtem',
    '25/02/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT004',
    'Nguefack',
    'Justine',
    '17/01/04',
    'F', 
    'justinenguefack@gmail.com',
    'JustNguefack',
    '06/05/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT005',
    'Bogni',
    'Doralice',
    '17/01/98',
    'F', 
    'bodora@gmail.com',
    'BoDora98',
    '25/05/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT006',
    'Eloundou',
    'Anita',
    '17/01/02',
    'F', 
    'elouneloun@gmail.com',
    '172022',
    '12/07/20'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT007',
    'Ekane',
    'Timote',
    '17/01/01',
    'M', 
    'tim@gmail.com',
    '20210117',
    '16/08/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT008',
    'Babana',
    'Ousmanou',
    '17/01/00',
    'M', 
    'babanou@gmail.com',
    'babana17',
    '29/04/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT009',
    'Zangue',
    'Sopita',
    '17/01/90',
    'F', 
    'sopitazangue@gmail.com',
    'sopita1990',
    '01/01/21'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT010',
    'Samba',
    'Ange',
    '17/01/05',
    'F', 
    'angesamba@gmail.com',
    'lovemyself17',
    '31/10/21'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT011',
    'Kamga',
    'Paul',
    '17/01/01',
    'M', 
    'paulkamga@gmail.com',
    '172001',
    '19/02/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT012',
    'Kagame',
    'Paul',
    '26/08/01',
    'M', 
    'paulkagame@gmail.com',
    'paulpaul',
    '19/02/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT013',
    'Embassa',
    'Vanessa',
    '27/12/99',
    'F', 
    'vanessaembassa@gmail.com',
    '2712',
    '31/10/21'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT014',
    'Owona',
    'Gabrielle',
    '11/11/99',
    'F', 
    'gabi@gmail.com',
    '1999',
    '29/04/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT015',
    'Tedongmo',
    'Valerie',
    '30/06/00',
    'F', 
    'valtedon@gmail.com',
    '2000',
    '16/08/22'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT016',
    'dongmo',
    'Vanelle',
    '30/06/03',
    'F', 
    'valdon@gmail.com',
    '2003',
    '01/01/21'
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT017',
    'Monga',
    'Jovanie',
    '30/06/03',
    'F', 
    'mongajovanie@gmail.com',
    '3006',
    '06/05/20'
);