INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT001',
    'Kenefack',
    'Jonnathan',
    TO_DATE('17/02/1992','dd/mm/yyyy'),
    'M', 
    'kenejonn@gmail.com',
    'ken89Joh17',
    TO_DATE('01/01/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT002',
    'Kenfack',
    'Jonan',
    TO_DATE('17/02/2002','dd/mm/yyyy'),
    'M', 
    'kenjonan@gmail.com',
    'jonan02',
    TO_DATE('23/02/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT003',
    'Temfack',
    'Joel',
    TO_DATE('17/01/1999','dd/mm/yyyy'),
    'M', 
    'joe@gmail.com',
    'temtem',
    TO_DATE('25/02/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT004',
    'Nguefack',
    'Justine',
    TO_DATE('17/01/2004','dd/mm/yyyy'),
    'F', 
    'justinenguefack@gmail.com',
    'JustNguefack',
    TO_DATE('06/05/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT005',
    'Bogni',
    'Doralice',
    TO_DATE('17/01/1998','dd/mm/yyyy'),
    'F', 
    'bodora@gmail.com',
    'BoDora98',
    TO_DATE('25/05/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT006',
    'Eloundou',
    'Anita',
    TO_DATE('17/01/2002','dd/mm/yyyy'),
    'F', 
    'elouneloun@gmail.com',
    '172022',
    TO_DATE('12/07/2020','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT007',
    'Ekane',
    'Timote',
    TO_DATE('17/01/2001','dd/mm/yyyy'),
    'M', 
    'tim@gmail.com',
    '20210117',
    TO_DATE('16/08/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT008',
    'Babana',
    'Ousmanou',
    TO_DATE('17/01/2000','dd/mm/yyyy'),
    'M', 
    'babanou@gmail.com',
    'babana17',
    TO_DATE('29/04/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT009',
    'Zangue',
    'Sopita',
    TO_DATE('17/01/1990','dd/mm/yyyy'),
    'F', 
    'sopitazangue@gmail.com',
    'sopita1990',
    TO_DATE('01/01/2021','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT010',
    'Samba',
    'Ange',
    TO_DATE('17/01/2005','dd/mm/yyyy'),
    'F', 
    'angesamba@gmail.com',
    'lovemyself17',
    TO_DATE('31/10/2021','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT011',
    'Kamga',
    'Paul',
    TO_DATE('17/01/2001','dd/mm/yyyy'),
    'M', 
    'paulkamga@gmail.com',
    '172001',
    TO_DATE('19/02/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT012',
    'Kagame',
    'Paul',
    TO_DATE('26/08/2001','dd/mm/yyyy'),
    'M', 
    'paulkagame@gmail.com',
    'paulpaul',
    TO_DATE('19/02/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT013',
    'Embassa',
    'Vanessa',
    TO_DATE('27/12/1999','dd/mm/yyyy'),
    'F', 
    'vanessaembassa@gmail.com',
    '2712',
    TO_DATE('31/10/2021','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT014',
    'Owona',
    'Gabrielle',
    TO_DATE('11/11/1999','dd/mm/yyyy'),
    'F', 
    'gabi@gmail.com',
    '1999',
    TO_DATE('29/04/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT015',
    'Tedongmo',
    'Valerie',
    TO_DATE('30/06/2000','dd/mm/yyyy'),
    'F', 
    'valtedon@gmail.com',
    '2000',
    TO_DATE('16/08/2022','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT016',
    'dongmo',
    'Vanelle',
    TO_DATE('30/06/2003','dd/mm/yyyy'),
    'F', 
    'valdon@gmail.com',
    '2003',
    TO_DATE('01/01/2021','dd/mm/yyyy')
);
INSERT INTO UTILISATEURS 
( 
    id_utilisateur,
    nom_utilisateur,
    prenom_utilisateur,
    date_naissance,
    genre,
    email_utilisateur,
    mot_de_passe,
    jour_inscription
)
VALUES
(
    'UT017',
    'Monga',
    'Jovanie',
    TO_DATE('30/06/2003','dd/mm/yyyy'),
    'F', 
    'mongajovanie@gmail.com',
    '3006',
   TO_DATE( '06/05/2020','dd/mm/yyyy')
);