ALTER TABLE MENUS
MODIFY id_menu INTEGER NOT NULL 
MODIFY intitule_menu VARCHAR(255) NOT NULL 
MODIFY date_debut DATE NOT NULL
MODIFY date_fin DATE NOT NULL 
MODIFY budget REAL NOT NULL
MODIFY id_repas INTEGER NOT NULL 
;