ALTER TABLE MENUS
ALTER COLUMN id_menu INTEGER NOT NULL 
ALTER COLUMN intitule_menu VARCHAR(255) NOT NULL 
ALTER COLUMN date_debut DATE NOT NULL
ALTER COLUMN date_fin DATE NOT NULL 
ALTER COLUMN budget REAL NOT NULL
ALTER COLUMN id_repas INTEGER NOT NULL 
;