ALTER TABLE NOTIFICATIONS 
ALTER COLUMN id_notification INTEGER NOT NULL;
ALTER COLUMN intitule_notification VARCHAR(255)NOT NULL ;
ALTER COLUMN contenu_notification VARCHAR(255)NOT NULL ;
ALTER COLUMN date_notification DATE NOT NULL ;
