ALTER TABLE NOTIFICATIONS 
MODIFY id_notification INTEGER NOT NULL
MODIFY intitule_notification VARCHAR(255)NOT NULL 
MODIFY contenu_notification VARCHAR(255)NOT NULL 
MODIFY date_notification DATE NOT NULL ;
