ALTER TABLE REPAS
  ALTER COLUMN  id_menu INTEGER NOT NULL ;
  ALTER COLUMN  nom_repas VARCHAR(20) , NOT NULL ;
  ALTER COLUMN  date_repas DATE NOT NULL;
  ALTER COLUMN  prix_repas REAL NOT NULL ;
  ALTER COLUMN  id_menu INTEGER  NOT NULL;
