ALTER TABLE SUIVI
  ALTER COLUMN  id_repas INTEGER NOT NULL ;
  ALTER COLUMN  id_notification INTEGER  NOT NULL ;
  ALTER COLUMN  masse_precedente REAL DATE NOT NULL;
  ALTER COLUMN  masse_actuelle REAL NOT NULL ;

