ALTER TABLE SUIVI ADD( 
    CONSTRAINT ID_MENU NOT NULL,
    CONSTRAINT ID_NOTIFICATION NOT NULL,
    CONSTRAINT MASSE_PRECEDENTE NOT NULL,
    CHECK(MASSE_PRECEDENTE>0),
    CONSTRAINT MASSE_ACTUELLE NOT NULL,
    CHECK(MASSE_ACTUELLE>0),
    FOREIGN KEY (ID_MENU) REFERENCES MENUS (ID_MENU),
    FOREIGN KEY (ID_NOTIFICATION) REFERENCES NOTIFICATIONS (ID_NOTIFICATION),
    PRIMARY KEY (ID_MENU, ID_NOTIFICATION)
);   