ALTER TABLE SUIVI ADD( 
    CONSTRAINT ID_MENU NOT NULL,
    CONSTRAINT ID_NOTIFICATION NOT NULL,
    CONSTRAINT MASSE_PRECEDENTE NOT NULL,
    CONSTRAINT MASSE_ACTUELLE NOT NULL,
    PRIMARY KEY (ID_MENU, ID_NOTIFICATION)
);    