ALTER TABLE HISTOTIQUE ADD(
    CONSTRAINT ID_HISTORIQUE NOT NULL,
    FOREIGN KEY (ID_MENU) REFERENCES MENUS (ID_MENU),
    FOREIGN KEY (ID_ABONNEMENT) REFERENCES ABONNEMENTS (ID_ABONNEMENT),
    PRIMARY KEY (ID_HISTORIQUE)
);