ALTER TABLE SUIVI ADD( 
    CONSTRAINT ID_MENU NOT NULL,
    CONSTRAINT ID_NOTIFICATION NOT NULL,
    CONSTRAINT MASSE_PRECEDENTE NOT NULL,
    CONSTRAINT MASSE_ACTUELLE NOT NULL,
    FOREIN KEY (ID_MENU) REFERENCES MENUS (ID_MENU),
    FOREIN KEY (ID_NOTIFICATION) REFERENCES NOTIFICATIONS (ID_NOTIFICATION),
    PRIMARY KEY (ID_MENU, ID_NOTIFICATION)
);    