@@Contrainte_Abonnement
@@contrainte_Calendrier
@@Contrainte_Historique
@@Contrainte_Informations_utilisateur
@@Contrainte_Ingredients_Repas
@@Contrainte_Ingredients
@@Contrainte_Menu
@@Contrainte_Notifications
@@Contrainte_Repas
@@Contrainte_Suivi
@@Contrainte_Type_Abonnement
@@Contrainte_Utilisateurs